# Helm Chart for OTPless Invoice Service
# Version: 1.0.0
# Maintainer: OTPless DevOps Team

apiVersion: v2
name: invoice-service
description: OTPless Invoice Service for automated invoice generation and management with high availability and scalability features
version: 1.0.0
appVersion: 1.0.0
type: application
kubeVersion: ">=1.27.0"

# Chart metadata and keywords
keywords:
  - invoice
  - billing
  - pdf-generation
  - otpless
  - high-availability
  - kubernetes

# Chart maintainers
maintainers:
  - name: OTPless Team
    email: devops@otpless.com

# Chart dependencies
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - cache
      - session
  - name: minio
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
    tags:
      - storage
      - documents

# Chart engine
engine: gotpl

# Chart annotations for ArtifactHub
annotations:
  artifacthub.io/changes: |
    - Initial release of Invoice Service Helm chart
    - Added Redis dependency for caching
    - Added MinIO dependency for storage
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "false"