# MinIO Helm values configuration
# Version: RELEASE.2023-10-07T15-07-38Z
# Purpose: Configure MinIO object storage for invoice and document storage

# Deployment mode - distributed for high availability
mode: distributed

# Image configuration
image:
  repository: minio/minio
  tag: RELEASE.2023-10-07T15-07-38Z
  pullPolicy: IfNotPresent

# High availability configuration
replicas: 4

# Resource allocation
resources:
  requests:
    memory: 4Gi
    cpu: "2"
  limits:
    memory: 8Gi
    cpu: "4"

# Persistent storage configuration
persistence:
  enabled: true
  storageClass: gp3
  size: 100Gi
  mountPath: /data

# Bucket configuration
buckets:
  - name: invoices
    policy: none
    purge: false
    versioning: true
  - name: documents
    policy: none
    purge: false
    versioning: true

# Security configuration
security:
  tls:
    enabled: true
    certSecret: minio-tls
  encryption:
    enabled: true
    kmsSecret: minio-kms

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - storage.otpless.com
  tls:
    - secretName: minio-tls
      hosts:
        - storage.otpless.com

# Monitoring configuration
monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s

# High availability settings
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Pod scheduling configuration
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - minio
        topologyKey: kubernetes.io/hostname

# Optional scheduling configurations
tolerations: []
nodeSelector: {}

# Service account configuration
serviceAccount:
  create: true
  annotations: {}

# Service configuration
service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

# Environment variables
env:
  - name: MINIO_BROWSER
    value: "on"
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: "public"

# API configuration
api:
  replicaCount: 4
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

# Console configuration
console:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate

# Network policy
networkPolicy:
  enabled: true
  allowExternal: true

# Readiness and liveness probes
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Backup configuration
backup:
  enabled: true
  schedule: "0 0 * * *"
  retention:
    enabled: true
    days: 30