# Kubernetes v1.27.x
# Purpose: Configuration settings for the invoice service deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-service-config
  namespace: otpless-billing
  labels:
    app: invoice-service
    component: backend
    environment: production
    team: otpless-devops
    managed-by: terraform
  annotations:
    description: "Invoice service configuration settings"
    maintainer: "otpless-devops"
    contact: "devops@otpless.com"
    last-updated: "2023-11-01"
data:
  # Service Identity Configuration
  APP_NAME: "otpless-invoice-service"
  APP_VERSION: "1.0.0"
  ENV: "production"
  
  # API Configuration
  API_PREFIX: "/api/v1"
  ALLOWED_HOSTS: |
    [
      "*.otpless.com",
      "api.otpless.com",
      "billing.otpless.com"
    ]
  CORS_ORIGINS: |
    [
      "https://*.otpless.com",
      "https://console.otpless.com",
      "https://billing.otpless.com"
    ]
  
  # Authentication Configuration
  JWT_ALGORITHM: "RS256"
  JWT_EXPIRY_MINUTES: "60"
  
  # Database Configuration
  DATABASE_URL: "postgresql://invoice_user:$(POSTGRES_PASSWORD)@rds.otpless-billing.svc.cluster.local:5432/invoice_db?sslmode=verify-full&sslcert=/etc/ssl/certs/rds-ca.pem"
  REDIS_URL: "redis://redis-master.otpless-billing.svc.cluster.local:6379/0"
  
  # Storage Configuration
  S3_BUCKET_NAME: "otpless-invoices-prod"
  AWS_REGION: "ap-south-1"
  
  # Business Logic Configuration
  SUPPORTED_CURRENCIES: |
    [
      "USD",
      "INR",
      "IDR"
    ]
  INVOICE_NUMBER_PREFIX: "INV"
  INVOICE_NUMBER_FORMAT: "{prefix}{year}{month}{sequence}"
  
  # Template Configuration
  PDF_TEMPLATE_PATH: "/app/templates/invoice.html"
  COMPANY_DETAILS: |
    {
      "name": "OTPless Technologies Pvt Ltd",
      "address": "Mumbai, Maharashtra, India",
      "gstin": "27AAFCO1234P1Z5",
      "pan": "AAFCO1234P"
    }
  
  # Performance Configuration
  MAX_WORKERS: "4"
  BATCH_SIZE: "100"
  REQUEST_TIMEOUT: "30"
  
  # Observability Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  
  # Rate Limiting Configuration
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_PERIOD: "60"
  
  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_ENABLED: "true"
  
  # Retry Configuration
  MAX_RETRIES: "3"
  RETRY_DELAY: "5"
  
  # Feature Flags
  FEATURES: |
    {
      "pdf_compression": true,
      "digital_signature": true,
      "email_notification": true,
      "webhook_notification": true
    }