# Kubernetes v1.27.x
# Purpose: Production deployment configuration for invoice service handling automated invoice generation and PDF processing

apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  namespace: otpless-billing
  labels:
    app: invoice-service
    component: backend
    part-of: billing-system
    environment: production
    team: otpless-devops
    managed-by: terraform
  annotations:
    description: "Invoice service for automated billing and PDF generation"
    maintainer: "otpless-devops"
    contact: "devops@otpless.com"
    security.otpless.com/compliance-level: "high"
spec:
  # High availability with 3 replicas as per 99.9% uptime requirement
  replicas: 3
  
  # Rolling update strategy for zero-downtime deployments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  selector:
    matchLabels:
      app: invoice-service
  
  template:
    metadata:
      labels:
        app: invoice-service
        component: backend
        part-of: billing-system
      annotations:
        # Prometheus metrics configuration
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        # Security scanning annotations
        security.otpless.com/scanned: "true"
        security.otpless.com/scan-date: "2023-11-01"
    
    spec:
      # Security context for non-root execution
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      # Service account for RBAC
      serviceAccountName: invoice-service-sa
      
      # Pod distribution and anti-affinity rules
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - invoice-service
              topologyKey: kubernetes.io/hostname
      
      # Container specification
      containers:
      - name: invoice-service
        image: otpless/invoice-service:latest
        imagePullPolicy: Always
        
        # Container security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        
        # Port configuration
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        
        # Resource limits as per container strategy
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        
        # Environment configuration from ConfigMap
        envFrom:
        - configMapRef:
            name: invoice-service-config
        
        # Liveness probe for container health
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Readiness probe for service availability
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        # Volume mounts for temporary data
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
      
      # Volumes configuration
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      
      # Pod termination grace period
      terminationGracePeriodSeconds: 60
      
      # Node selector for production workloads
      nodeSelector:
        type: application
        environment: production
      
      # Tolerations for node taints
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "application"
        effect: "NoSchedule"